server/dashboard/urls.py
from . import views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls.conf import path
from django.conf.urls.i18n import i18n_patterns


app_name = 'dashboard'

urlpatterns = [
    path(r'home/', views.index, name = 'index'),
    path(r'upgrade/', views.upgrade, name='upgrade'),
    path(r'notification_settings/', views.notification_setting, name='notification_setting'),
    path(r'delete_account/', views.delete_account, name='delete_account'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^project/list/$', views.project_list, name='project_list'),
    url(r'^project/list/i18n/', include('django.conf.urls.i18n')),
    #path(r'project/schedule/', views.project_schedule, name = 'project_schedule'),
    path(r'settings/', views.settings, name='settings'),
    path(r'notification/change/', views.notification_change, name='notification_change'),
    url(r'account_setting_basic/$', views.account_setting_basic, name='account_setting_basic'),
    url(r'profile_change/$', views.profile_change, name='profile_change'),
    url(r'profile_change_finish/$', views.profile_change_finish, name='profile_change_finish'),
    url(r'password_change/$', views.PasswordChange.as_view(), name='password_change'),
    url(r'password_change_finish/$', views.password_change_finish, name='password_change_finish'),
    url(r'agreement_payment/$', views.agreement_payment, name='agreement_payment'),
    url(r'payment_change_bank/$', views.payment_change_bank, name='payment_change_bank'),
    url(r'payment_change_credit/$', views.payment_change_credit, name='payment_change_credit'),
    url(r'payment_change_finish/$', views.payment_change_finish, name='payment_change_finish'),
    url(r'product_download/$', views.product_download, name='product_download'),
    url(r'system_error/$', views.system_error, name='system_error'),
    # url(r'cancel/$', views.cancel, name='cancel'),
    # url(r'cancel_finish/$', views.cancel_finish, name='cancel_finish'),
    path(r'ajax/$', views.managefiletype, name='managefiletype'),
    path(r'ajax1/$', views.edit_project, name='edit_project'),
    path(r'ajax2/$', views.edit_keyword, name='edit_keyword'),
    path(r'update/profile/', views.update_profile, name='update_profile'),
    path(r'project/data_order/', views.data_order, name='data_order'),
    path(r'project/data_order_form/', views.data_order_form, name='data_order_form'),
    path(r'project/data_order_confirm/', views.data_order_confirm, name='data_order_confirm'),
    path(r'project/data_order_done/', views.data_order_done, name='data_order_done'),

    #path(r'ScheduleForm/', views.schedule_form, name = 'schedule_form'),
    url(r'run/(?P<pid>[^/]+)$', views.run, name='run'),
    path(r'zip_data/(?P<pid>[^/]+)$', views.zip_data, name='zip_data'),
    path(r'delete/(?P<str:cname>[^/]+)$', views.delete_category, name='delete_category'),
    path(r'delete/(?p<pid>[^/]+)$', views.delete_project, name='delete_project'),
    path(r'delete_execution/(?P<pid>[^/]+)/(?P<eid>[^/]+)$', views.delete_execution, name='delete_execution'),
    url(r'product/$', views.product_type, name='product_type'),
    url(r'project/details/(?P<pid>[^/]+)$', views.project_details, name='project_details'),
    url(r'get_project/', views.get_project, name='get_project'),
    url(r'auto_refresh/', views.auto_refresh, name='auto_refresh'),

    url(r'email_change/$', views.email_change, name='email_change'),

    #---------Payment-------------------------------------------
    url(r'^cart$', views.ShowCartView.as_view(), name='cart'),
    #url(r'^create-payment$', views.CreatePaymentView.as_view(), name='create-payment'),
    #url(r'^execute-payment$', views.ExecutePaymentView.as_view(), name='execute-payment'),
    url(r'upgrade/payment', views.ExecutePaymentView, name='ExecutePaymentView'),
]

server/global_dashboard/urls.py
from . import views
from . import  analyze as analyze_views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = 'global_dashboard'

urlpatterns = [
    url(r'global/home/$', views.global_home, name='index'),
    url(r'global/new/project$', views.new_project, name='new_project'),
    url(r'global/projects/$', views.global_project_list, name='all_projects'),
    url(r'ajax/(?P<uid>[^/]+)/(?P<pid>[^/]+)/(?P<eid>[^/]+)/(?P<ft>[^/]+)$', views.product_type, name='product_type'),
    url(r'running/(?P<pid>[^/]+)$', views.run_now, name='run_now'),
    path(r'global/delete/(?p<pid>[^/]+)$', views.global_delete_project, name='global_delete_project'),
    url(r'^project/list/i18n/', include('django.conf.urls.i18n')),
    url(r'global/profile/$', views.profile, name='profile'),
    url(r'global/setting/$', views.setting, name='setting'),
    url(r'global/activity_log/$', views.activity_log, name='activity_log'),
    url(r'global/feedback/$', views.post_feedback, name='feedback'),
    url(r'global/instructions/$', views.instructions, name='instructions'),
    path(r'ajax_project/$', views.edit_project, name='edit_project'),
    path(r'ajax_keyword/$', views.edit_keyword, name='edit_keyword'),

    url(r'global/profile/$', views.profile, name='profile'),
    url(r'global/analyze/$', analyze_views.analyze, name='analyze'),
    url(r'global/activity/$', views.activity, name='activity'),
    url(r'global/settings/$', views.settings, name='settings'),

    url(r'global/data_order/', views.data_order, name='data_order'),
    url(r'global/data_order_form/', views.data_order_form, name='data_order_form'),
    url(r'global/data_order_confirm/', views.data_order_confirm, name='data_order_confirm'),
    url(r'global/data_order_done/', views.data_order_done, name='data_order_done'),
    url(r'global/password_change/$', views.PasswordChange.as_view(), name='password_change'),
    url(r'global/password_change_finish/$', views.password_change_finish, name='password_change_finish'),
    url(r'global/email_change/$', views.email_change, name='email_change'),
    url(r'global/cancel/$', views.cancel, name='cancel'),
    url(r'global/cancel_finish/$', views.cancel_finish, name='cancel_finish'),
]

server/saas/urls.py
from . import views as core_views
from django.conf.urls import url

app_name = 'saas'

urlpatterns = [
    url(r'^saas/start/', core_views.start, name='start'),
    url(r'^saas/getLogin', core_views.get_login, name='get_login'),
    url(r'^saas/content', core_views.url_content_sel, name='url_content_sel'),
    url(r'^saas/procedure', core_views.get_procedure, name='get_procedure'),
    url(r'^saas/', core_views.process, name='process'),
    url(r'^pigdata-saas/', core_views.pigdata, name='pigdata'),
]

server/web_rpa/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    #path('', RedirectView.as_view(url='dashboard')),
    path('', include('accounts.urls')),
    path('api/v1/core/', include('api_v1.core.urls')),
    path('api/v1/feedback/', include('api_v1.feedback.urls')),
    #path('api/v1/scheduling/', include('api_v1.scheduling.urls')),
    path('api/v1/scraping/', include('api_v1.scraping.urls')),
    path('admin/', admin.site.urls),
    path('', include('saas.urls')),
    path('', include('dashboard.urls')),
    path('', include('global_dashboard.urls')),
    path('email/', include('email_sys.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('', include('social_django.urls', namespace='social')),
]


server/accounts/models.py
from __future__ import unicode_literals
from django.conf import settings
from datetime import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser, BaseUserManager ## A new class is imported. ##
from django.db import models
from django.utils.translation import ugettext_lazy as _
import os
import sys

import pytz

data_folder = settings.SCRAPING_DATA_DIR

class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
             raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)




class User(AbstractUser):
    """User model."""
    #username = None
    email = models.EmailField(_('email address'), unique=True)
    old_email = models.EmailField(null=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager() ## This is the new line in the User model. ##

    def last_name(self):
        return self.profile.last_name

    def first_name(self):
        return self.profile.first_name        

    def project_counts(self):
        from api_v1.scraping.models import Project
        num_proj = Project.objects.filter(user_id=self.id)
        return len(num_proj)

    def project_size(self):
        from api_v1.scraping.models import Project
        total_size = 0
        prj = Project.objects.filter(user_id=self.id)
        for project in prj:
            total_size = total_size + int(project.project_size or 0)

        g = 1024 * 1024 * 1024
        m = 1024 * 1024
        k = 1024

        show_size = round(total_size / m, 1)
        return show_size


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    notification = models.BooleanField(default=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    first_name_kana = models.CharField(max_length=15, blank=True)
    last_name_kana = models.CharField(max_length=15, blank=True)

    company_name = models.CharField(max_length=30, blank=True)
    company_name_kana = models.CharField(max_length=30, blank=True)
    department = models.CharField(max_length=30, blank=True)
    job_title = models.CharField(max_length=30, blank=True)
    tel_number = models.CharField(max_length=18, blank=True)
    post_code = models.CharField(max_length=10, blank=True)
    address = models.CharField(max_length=50, blank=True)

    public_key = models.CharField(max_length=1024, blank=True)
    private_key = models.CharField(max_length=1024, blank=True)

    is_agree_user_pol = models.BooleanField(default=False)
    is_agree_privacy_pol = models.BooleanField(default=False)
    is_agree_security_pol = models.BooleanField(default=False)

    timezone = models.CharField(max_length=100, choices=tuple(zip(pytz.all_timezones, pytz.all_timezones)), default='UTC')


    def __str__(self):
        return self.first_name_kana + "   " + self.last_name_kana

    def full_name_kana(self):
        return self.last_name_kana + "   " + self.first_name_kana  
    full_name_kana.short_description = 'full name (kana)'

    def full_name(self):
        return self.last_name + "   " + self.first_name
    full_name.short_description = 'full name'

    def emailid(self):
        return self.user.email
    emailid.short_description = "email"

    def staffstat(self):
        return self.user.is_staff


class Data_Order(models.Model):
    user          = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    url_list      = models.CharField(max_length=100)
    data_details  = models.CharField(max_length=200, blank=True)
    due_date      = models.DateField()
    purpose       = models.CharField(max_length=100)
    budget        = models.CharField(max_length=30)
    company       = models.CharField(max_length=30)
    department    = models.CharField(max_length=30)
    email         = models.CharField(max_length=100)
    phone_number  = models.CharField(max_length=15)
    regular_order = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=datetime.now)


server/dashboard/models.py
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db.models.signals import post_save

from api_v1.scraping.models import Execution
from api_v1.scraping.models import Project
from django_celery_results.models import TaskResult

from django.utils import timezone

from celery.signals import task_prerun, task_postrun
import celery.states as celery_state

from api_v1.scraping.tasks import task_scrape

@task_prerun.connect
def pre_run(sender, task_id, task, *args, **kwargs):
    task.__task_starttime = timezone.now()
    return

@task_postrun.connect
def post_run(sender, task_id, task, retval, state,  *args, **kwargs):
    end_time = timezone.now()
    start_time = getattr(task, "__task_starttime", None)

    #check
    #print(isinstance(sender, type(task_scrape)))
    #if(sender == task_scrape):
    if(not(start_time is None)):
        if(sender.name == task_scrape.name):
            #task_scrape task
            try:
                exec_time = end_time - start_time
                task_project = Project.objects.get(id=kwargs['args'][1])
                task_result = TaskResult.objects.get(task_id=task_id)
                #task_state is 0 for every completed state (FAILED, REVOKED) other than success
                task_state = True if state == celery_state.SUCCESS else False
                
                res = Execution.objects.create(task=task_result, status=task_state, project=task_project, 
                                            date_executed=start_time, end_time=end_time, exec_time=exec_time)
            except Exception as e:
                print("task_postrun exception:", e)
                import traceback
                print(traceback.print_tb(e.__traceback__))
        else:
            #Other tasks
            pass
    else:
        print("task_starttime variable NOT FOUND!!! Could not write the task in Execution table!!!")
    return

server/dashboard/templates/cancel_finish.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}解約完了{% endblock %}

{% block css %}
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
{% endblock %}

{% block js %}
<script src="{% static 'assets/js/pig_web_common.js' %}" type="text/javascript"></script>
<script type="text/javascript">
    setTimeout(function(){
        window.location.href = "https://services.sms-datatech.co.jp/pig-data/";
    }, 5*1000);
</script>
{% endblock %}

{% block content %}
<div style="height: 87vh;">
	<div class="title">
		<h2>解約</h2>
	</div>
	<div class="plan_wrapper">
		<div class="plan_form_wrapper">
			<p style="font-size: 20px; text-align: center;">解約完了いたしました。<br />ご利用誠にありがとうございました。</p>
		</div>
		<div class="plan_form_wrapper">
			<p class="align_right" style="margin-top: 100px;"><a href="https://services.sms-datatech.co.jp/pig-data/">製品トップページへ戻る</a></p>
		</div>
	</div>


</div>
{% endblock %}

server/dashboard/templates/data_order_done.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}Data Order{% endblock %}

{% block content %}
        <div class="main-panel" style="width: 50%;">
            <div class="content">
                <div class="container-fluid">
                    <div class="card">
                        <div class="heading">
                            <h4 class="title">{% trans "Data Order Form" %}</h4>
                        </div>
                        <div class="card-content" style="margin: 40px 20px;">
                            <div class="table-responsive table-upgrade">
                                {% trans "Data order has been completed. The representative will contact you by 3 business days" %}<br><br>
                                {{ email }}{% trans "We sent a mail. Please confirm." %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

server/dashboard/templates/profile_change.html
{% extends "base-global.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Profile Change" %}{% endblock %}

{% block css %}
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
<div id="setting_menu">
    {% include 'common/account_setting.html' with selected_tab=2 %}
</div>
<div id="menu_bottom_line"></div>
<div class="row setting_main">
		<p class="setting_title"><b class="border_bottom">{% trans "Profile Change" %}</b></p>
		<div class="profile_change_wrapper">
        <p class="caution"><sup>*</sup>{% trans "Mandatory fields" %}</p>
        {% if messages %}
            <div class="alert alert-info" role="alert" style="width: 800px; text-align: center; font-size: 18px;">
                {% trans "You changed the member information successfully." %}
            </div>
        {% endif %}

        {% if profile_form.errors %}
            <div class="alert alert-danger" role="alert">
                {{ profile_form.errors }}
            </div>
        {% endif %}
        <form method="post" id="submit_form" action="{% url 'dashboard:profile_change' %}">
            {% csrf_token %}
            <div class="row">
	                <div class="col-md-4">
                      <div class="form-group"><b>{% trans "User ID" %}</b></div>
	                </div>
	                <div class="col-md-6">
                      <div class="form-group">{{ user.username }}</div>
	                </div>
	            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group"><b>{% trans "Your Name" %}</b><sup>*</sup></div>
                </div>
                <div class="col-md-1">
                    <div class="form-group" style="margin: 45px 0 0 0;">{% trans "Last Name" %}</div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">{{ profile_form.last_name }}</div>
                </div>
                <div class="col-md-1">
                    <div class="form-group" style="margin: 45px 0 0 0;">{% trans "First Name" %}</div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">{{ profile_form.first_name }}</div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group"><b>{% trans "Your Name (kana)" %}</b><sup>*</sup></div>
                </div>
                <div class="col-md-1">
                    <div class="form-group" style="margin: 45px 0 0 0;">{% trans "Last Name (kana)" %}</div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">{{ profile_form.last_name_kana }}</div>
                </div>
                <div class="col-md-1">
                    <div class="form-group" style="margin: 45px 0 0 0;">{% trans "First Name (kana)" %}</div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">{{ profile_form.first_name_kana }}</div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group"><b>{% trans "Company Name" %}</b><sup>*</sup></div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">{{ profile_form.company_name }}</div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group"><b>{% trans "Company (kana)" %}</b><sup>*</sup></div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">{{ profile_form.company_name_kana }}</div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group"><b>{% trans "Department" %}</b></div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">{{ profile_form.department }}</div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group"><b>{% trans "Position" %}</b></div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">{{ profile_form.job_title }}</div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group"><b>{% trans "Phone Number" %}</b><span style="font-size: 11px;">&nbsp;({% trans "without dash" %})</span></div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">{{ profile_form.tel_number }}</div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group"><b>{% trans "Postal Code" %}</b><span style="font-size: 11px;">&nbsp;({% trans "without dash" %})</span><br />
                        <span class="font_small">{% trans "It is mandatory when paying with invoice" %}</span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">{{ profile_form.post_code }}</div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group"><b>{% trans "Address" %}</b><br /><span class="font_small">{% trans "It is mandatory when paying with invoice" %}</span></div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">{{ profile_form.address }}</div>
                </div>
            </div>
            <div class="pay_change_btn"><button type="submit" id="btn_profile" class="btn mypage">{% trans "Send Email" %}</button></div>
        </form>
		</div>
		<div class="menu_bottom_line_2"></div>
		<p class="setting_title">
        <b class="border_bottom">{% trans "Change Password" %}</b>
    </p>
		<div class="profile_change_wrapper">
			  <p class="align_right">{% trans "Change Password is" %}<a href="{% url 'dashboard:password_change' %}">{% trans "Here" %}</a></p>
		</div>

    <!-- Email changing form -->
		<p class="setting_title">
        <b class="border_bottom">{% trans "Change Email" %}</b>
    </p>
    <div class="profile_change_wrapper">
          <p class="align_right">{% trans "Change Email is" %}<a id="change_email_btn">{% trans "Here" %}</a></p>
    </div>
    <form id="change_email_form">
        {% csrf_token %}
        <tr>
            <td><b>{% trans "New email address" %}:</b></td>
            <td><input type="email" name="email" id='new_email' class="form-control"></td>
        </tr>
        <tr>
            <td><b>{% trans "Re-enter new email address" %}:</b></td>
            <td><input type="email" name="confirm_email" id='confirm_email' class="form-control"></td>
        </tr>
        <button type="submit" id="submit" class="btn mypage" style="margin-bottom:10px; margin-left: 30px;">{% trans "Change Your email" %}</button>
    </form>

		<p class="setting_title">
        <b class="border_bottom">{% trans "Cancellation of PigData" %}</b>
    </p>
		<div class="profile_change_wrapper">
		    <p class="align_right" style="margin-bottom:100px;">{% trans "Cancellation of PigData is" %}<a href="{% url 'dashboard:cancel' %}">{% trans "Here" %}</a></p>
		</div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'assets/js/jquery.autoKana.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/jquery.jpostal.js' %}" type="text/javascript"></script>
<script type="text/javascript">
    $(function() {
        $.fn.autoKana('#id_last_name', '#id_last_name_kana', {
        	  katakana : true
        });
    });
    $(function() {
        $.fn.autoKana('#id_first_name', '#id_first_name_kana', {
            katakana : true
        });
    });
    $(function() {
        $.fn.autoKana('#id_company_name', '#id_company_name_kana', {
            katakana : true
        });
    });
    $(document).ready(function () {
        $('#id_post_code').jpostal({
            postcode : [
                '#id_post_code'
            ],
            address : {
                '#id_address' : '%3%4%5'
            },
            url : {
                'http'  : '/json/',
                'https' : '/json/'
            }
        });
    });

    //activate form button when user input form content
    $("#btn_profile").prop("disabled", true);
    $(function() {
        $('input[type="text"]').change(function() {
            $("#btn_profile").prop("disabled", false);
        });
    });
</script>

<!-- custom script for email_change toggling -->
<!--script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" type="text/javascript"></script-->
<script type="text/javascript">
    $(document).ready(function(){
        $("#change_email_btn").click(function(){
            $("#change_email_form").toggle();
        });
    });

    $("#change_email_form").on("submit", function(){
        if($("#new_email").val() != $("#confirm_email").val()) {
            alert("Emails doesn't match!");
            return;
        }

        formData = {};
        $('#change_email_form').find("input[name]").each(function (index, node) {
            formData[node.name] = node.value;
        });

        //check user.id
        formData['uid'] = {{ user.id }};

        message = ''
        $.ajax({
            url : "{% url 'dashboard:email_change' %}",
            type : "POST",
            data : formData,

            // handle a successful response
            success : function(json) {
                message = 'Activation email sent to your new email-address. Please follow those instructions to complete your email verification.';
            },
            // handle a non-successful response
            error : function(xhr, errmsg, err) {
                message = errmsg;
            }
        });

        $("#change_email_form").toggle();
    });
</script>
{% endblock %}

server/dashboard/templates/profile_change_email.html
{% autoescape off %}
===================================
PigData　登録情報 変更通知
===================================
お客様のPigDataアカウントに登録されている基本情報に
変更がありました。
下記のURLより内容を確認してください。

https://pig-data.sms-datatech.co.jp/account_setting_basic/

(クリックできない場合はブラウザーのアドレス欄にコピーしてください)


【 ご 注 意 】
※このメールにお心当たりのない場合、大変お手数ですが、
　support@sms-datatech.zendesk.comまでご連絡をお願い申し上げます。


発行元：株式会社SMSデータテック
<support@sms-datatech.zendesk.com>
〒104-0043　東京都中央区湊3-5-10 VORT新富町3F
{% endautoescape %}