server/accounts/urls.py
from . import views
from . import views as core_views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    # url(r'home/$', core_views.home, name='home'),
    url(r'products/$', core_views.product, name='product'),
    url(r'learn/$', core_views.learn, name='learn'),
    url(r'about/$', core_views.about, name='about'),

    #url(r'testing/(?P<pid>[^/]+)$', core_views.testing, name='testing'),
    url(r'pricing/$', core_views.pricing, name='pricing'),
    url(r'^login/', views.login, name='login'),

    #url(r'^$', auth_views.logout, {'next_page': 'home'}, name='logout'),
    url(r'logout/$', views.logout_view, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^signup-confirm/$', core_views.signupConfirm, name='signupConfirm'),
    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    url(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
    url(r'^error/$', core_views.error, name='error'),
    url(r'downloadtool/$', views.downloadtool, name='downloadtool'),
    url(r'json/(?P<value>\d{3}).json', views.postal_json, name='postal_json_data'),
    url(r'account_activation/$', core_views.account_activation, name='account_activation'),

    # ---------------Password Reset------------------------------
    url(r'^password_reset/$', auth_views.password_reset,
        {'email_template_name': 'registration/password_reset_email.html',
         'subject_template_name': 'registration/password_reset_subject.txt',
         'post_reset_redirect': 'accounts:password_reset_done',
         'from_email': 'no-reply@sms-datatech.co.jp',
         }, name='password_reset'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^password_reset/done/$', auth_views.password_reset_done,
        {'template_name': 'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[^/]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    # global
    url(r'^$', core_views.global_home, name='global_home'),
    url(r'global/login/$', core_views.global_login, name='global_login'),
    url(r'global/contact/$', core_views.global_contact, name='global_contact'),
    url(r'global/signup/$', core_views.global_signup, name='global_signup'),

    url(r'resend_link/$', core_views.ResendLinkView.as_view(), name='resend_link'),
    url(r'resend_link_done/$', core_views.ResendLinkDoneView.as_view(), name='resend_link_done'),
]

server/saas/urls.py
from . import views as core_views
from django.conf.urls import url

app_name = 'saas'

urlpatterns = [
    url(r'^saas/start/', core_views.start, name='start'),
    url(r'^saas/getLogin', core_views.get_login, name='get_login'),
    url(r'^saas/content', core_views.url_content_sel, name='url_content_sel'),
    url(r'^saas/procedure', core_views.get_procedure, name='get_procedure'),
    url(r'^saas/', core_views.process, name='process'),
    url(r'^pigdata-saas/', core_views.pigdata, name='pigdata'),
]

server/web_rpa/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    #path('', RedirectView.as_view(url='dashboard')),
    path('', include('accounts.urls')),
    path('api/v1/core/', include('api_v1.core.urls')),
    path('api/v1/feedback/', include('api_v1.feedback.urls')),
    #path('api/v1/scheduling/', include('api_v1.scheduling.urls')),
    path('api/v1/scraping/', include('api_v1.scraping.urls')),
    path('admin/', admin.site.urls),
    path('', include('saas.urls')),
    path('', include('dashboard.urls')),
    path('', include('global_dashboard.urls')),
    path('email/', include('email_sys.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('', include('social_django.urls', namespace='social')),
]


server/accounts/views.py
from django.contrib.auth import login
from django.http.request import HttpRequest
from django.http.response import HttpResponse, JsonResponse, HttpResponseRedirect
import os
import requests
from .models import User
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
import mimetypes
from wsgiref.util import FileWrapper
from .forms import UserForm, ProfileForm
from email_sys.tokens import account_activation_token
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control
from .models import Profile
from datetime import datetime
from Crypto.PublicKey import RSA
from django.contrib.auth.views import login
from django.conf import settings

from django.db import transaction

from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth import update_session_auth_hash

from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.forms import PasswordResetForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy

from .decorators import anonymous_required

UserModel = get_user_model()

class ResendLinkForm(PasswordResetForm):

    """Form subclassing PasswordResetForm (for Resend_Activation_Link feature)
    """
    
    def get_users(self, email):
        """Get the list of users to send the mail
        
        Args:
            email (TYPE): Description
        
        Returns:
            TYPE: Description
        """
        active_users = UserModel._default_manager.filter(**{
            '%s__iexact' % UserModel.get_email_field_name(): email,
            'is_active': False,
        })
        return (u for u in active_users)


class ResendLinkView(PasswordResetView):

    """View subclassing PasswordResetView (for Resend_Activation_Link feature)
    
    Attributes:
        email_template_name (str): Name of email template to send
        form_class (TYPE): Class name of the form (asking for email address)
        from_email (str): Email address of the sender
        subject_template_name (str): Subject for the email
        success_url (TYPE): Redirect URL after SUCCESS
        template_name (str): Template for the form
        title (TYPE): Title for the form template
        token_generator (TYPE): Token generator class
    """
    
    form_class = ResendLinkForm
    title = _("Resend Activation Link")
    token_generator = account_activation_token
    template_name = "registration/resend_activation_link_form.html"
    success_url = reverse_lazy('accounts:resend_link_done')
    email_template_name = 'registration/resend_activation_link_email.html'
    subject_template_name = 'registration/resend_activation_link_subject.txt'
    from_email = 'no-reply@sms-datatech.co.jp'


class ResendLinkDoneView(PasswordResetDoneView):

    """View subclassing PasswordResetDoneView (for Resend_Activation_Link feature)
    
    Attributes:
        template_name (str): Template to display after activation link is sent
        title (TYPE): Title for the template
    """
    
    template_name = 'registration/resend_activation_link_done.html'
    title = _('Resent activation link')

def home(request):
    # return HttpResponseRedirect('https://services.sms-datatech.co.jp/pig-data/')
    return render(request, 'home.html')
def product(request):
    return render(request, 'product.html')
def learn(request):
    return render(request, 'learn.html')
def about(request):
    return render(request, 'about.html')
def contact(request):
    return render(request, 'contact.html')
def pricing(request):
    return render(request, 'pricing.html')

# global views
@anonymous_required
def global_home(request):
    return render(request, 'global-home.html')

@anonymous_required
def global_login(request):
    return render(request, 'global-login.html')

def global_contact(request):
    return render(request, 'contacts.html')

def get_client_ip(request: HttpRequest):
    """Function to get the client IP address
    
    Args:
        request (HttpRequest): Description
    
    Returns:
        TYPE: Description
    """
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR', None)
    if(x_forwarded_for):
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

def get_user_timezone(request: HttpRequest):
    """Function to get the user timezone from IP address
    
    Args:
        request (HttpRequest): Description
    
    Returns:
        TYPE: Description
    """
    client_ip = get_client_ip(request)
    resp = requests.get('http://freegeoip.app/json/{0}'.format(client_ip))
    resp_json = resp.json()
    return resp_json['time_zone']

@anonymous_required
def global_signup(request):
    print('>>INSIDEShamik')
    user_form    = UserForm()
    profile_form = ProfileForm()
    if request.method == 'POST':

        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)
        user_timezone = None

        try:
            user_timezone = get_user_timezone(request)
        except Exception as e:
            print("SIGNUP TIMEZONE ERROR:", e)
        if user_form.is_valid() and profile_form.is_valid() and user_timezone is not None:
            try:
                # with transaction.atomic():
                user = user_form.save(commit=False)
                user.is_active = False
                user.save()
                print('user saved')
                #profile
                profile = profile_form.save(commit=False)
                profile.timezone = user_timezone
                profile.user = user
                key_pair = RSA.generate(1024)
                profile.private_key = key_pair.exportKey().decode()
                profile.public_key = key_pair.publickey().exportKey().decode()
                profile.save()

                return render(request, 'account_activation_sent.html')
            except Exception as e:
                print(e)
                return render(request, 'error.html')
        else:
            print(user_form.errors)
            print(profile_form.errors)
            print("User timezone:", user_timezone)
            return render(request, 'global-sign-up.html', {'user_form': user_form, 'profile_form': profile_form})

    return render(request, 'global-sign-up.html', {'user_form': user_form, 'profile_form': profile_form})

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required()
def logout_view(request, *args, **kwargs):
    auth_views.logout(request)
    request.session.flush()
    domain = get_current_site(request).domain
    #production
    if domain == "pig-data.sms-datatech.co.jp":
        return HttpResponseRedirect('https://pig-data.sms-datatech.co.jp/')
    #develop
    else:
        return HttpResponseRedirect('/')

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@anonymous_required
def login(request, *args, **kwargs):
    return auth_views.login(request, 'global-login.html')

@anonymous_required
def signup(request):
    user_form = UserForm()
    profile_form = ProfileForm()
    if request.method == 'POST' and 'signup' in request.POST:
        user_timezone = None

        try:
            user_timezone = get_user_timezone(request)
        except Exception as e:
            print("SIGNUP TIMEZONE ERROR:", e)

        user_form = UserForm(request.POST)
        if user_form.is_valid():
            try:
                #user
                user = user_form.save(commit=False)
                user.is_active = False
                user.save()
            except Exception as e:
                print(e)
                return render(request, 'error.html')

            profile_form = ProfileForm(request.POST)
            key_pair = RSA.generate(1024)
            if profile_form.is_valid():
                try:
                    #profile
                    profile = profile_form.save(commit=False)
                    profile.user = user
                    profile.timezone = user_timezone
                    profile.private_key = key_pair.exportKey().decode()
                    profile.public_key = key_pair.publickey().exportKey().decode()
                    print(key_pair.publickey().exportKey().decode())
                    print('____________________\n')
                    print(key_pair.publickey().exportKey())

                    profile.save()
                    return render(request, 'account_activation_sent.html')
                except Exception as e:
                    print(e)
                    return render(request, 'error.html')

            else:
                print(profile_form.errors)
                return render(request, 'signup.html', {'user_form': user_form, 'profile_form': profile_form})
        else:
            print(user_form.errors)
            return render(request, 'signup.html', {'user_form': user_form, 'profile_form': profile_form})
    elif request.method == 'POST' and 'edit' in request.POST:
        user_form    = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)
    return render(request, 'signup.html', {'user_form': user_form, 'profile_form': profile_form})

def signupConfirm(request):
    if request.method == 'POST':
        user_form    = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid() :
            return render(request, 'signup-confirm.html', {'user_form': user_form, 'profile_form': profile_form})
        else:

server/accounts/templates/account_activation_sent.html
{% extends "base-global.html" %}
{% load static %}
{% load i18n %}

{% block title %}Sign up{% endblock %}

{% block css %}
{% endblock %}

{% block js %}
<!--<script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>-->
{% endblock %}

{% block content %}
<section id="intro" class="clearfix">
    <div class="container d-flex h-100">
      <div class="row justify-content-center align-self-center">
        <div class="col-md-6 intro-info order-md-first order-last">
          <div>
            <h3 class="align_center" style="margin: 50px 0;">{% trans "Registration Finished." %}</h3>
            <p class="align_left">
                {% trans "To verify your e-mail address an activation link has been sent to the registered e-mail address." %}<br />
            </p>
            <br><br><br>
          </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}

server/accounts/templates/contact.html
{% extends "product_site_base.html" %}
{% load static %}
{% load i18n %}
{% block content%}
<div class="navbar">
	<a href="{% url 'accounts:home' %}" >Home</a>
	<a href="{% url 'accounts:product' %}" >{% trans "Products" %}</a>
	<a href="{% url 'accounts:learn' %}">{% trans "Learn" %}</a>
	<a href="{% url 'accounts:pricing' %}">{% trans "Pricing" %}</a>
	<a href="{% url 'accounts:about' %}">{% trans "About Us" %}</a>
	<a href="{% url 'accounts:contact' %}" class="active">{% trans "Contacts" %}</a>
	<a href="{% url 'accounts:login' %}" >{% trans "Login" %}</a>

	<!--div class="dropdown">
		<button class="dropbtn">en
			<i class="fa fa-caret-down"></i>
		</button>
		<div class="dropdown-content">
			<form>
			<a href="#" >ja</a>
			</form>
		</div>
	</div-->
</div>
<h2 class="major">{% trans "Contact" %}</h2>
			<form method="post" action="#">
				<div class="field half first">
					<label for="name">{% trans "Name" %}</label>
					<input type="text" name="name" id="name" />
				</div>
				<div class="field half">
					<label for="email">{% trans "Email" %}</label>
					<input type="text" name="email" id="email" />
				</div>
				<div class="field">
					<label for="message">{% trans "Message" %}</label>
					<textarea name="message" id="message" rows="4"></textarea>
				</div>
				<ul class="actions">
					<input type="submit" value="Send Message" class="special" />
					<input type="reset" value="Reset" />
				</ul>
			</form>

{% endblock%}

server/accounts/templates/global-login.html
{% extends "base-global.html" %}
{% load static %}
{% load i18n %}

{% block meta%}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
{% endblock%}

{% block title%}
  {% trans "Login" %}
{% endblock%}

{% block css%}
  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="css/sb-admin-2.min.css" rel="stylesheet">
{% endblock%}

{% block content%}
    <!-- Outer Row -->
<section class="login" id="login">
    <div class="container">
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                      <h1 class="h4 text-gray-900 mb-4">{% trans "Welcome" %}</h1>
                  </div>
                  {% if form.non_field_errors %}
                    <ul class='form-errors'>
                      {% for error in form.non_field_errors.as_data %}

                        <li>{{ error.messages|first }}</li>
                          {% if error.code == "inactive" %}
                              <a class="small" href="{% url 'accounts:resend_link' %}">Resend activation email?</a>
                          {% endif %}
                      {% endfor %}
                    </ul>
                  {% endif %}
                  <form class="form-signin" method="post" action="{% url 'accounts:login' %}">
                    {% csrf_token %}
                    <div class="form-group">
                       <input type="text" class="form-control inputUsername" name="username" maxlength="254" required id="id_username" placeholder="Email" autofocus>
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control inputPassword" name="password" required id="id_password" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">{% trans "Remember Me" %}</label>
                      </div>
                    </div>
                    <!--<a href="index.html" class="btn btn-primary btn-user btn-block">-->
                      <!--Login-->
                    <!--</a>-->
                    <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">{% trans "Login" %}</button>
                    <hr>
                    <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-google btn-user btn-block">
                      <i class="fab fa-google fa-fw"></i> {% trans "Login with Google" %}
                    </a>
                    <a href="{% url 'social:begin' 'facebook' %}" class="btn btn-facebook btn-user btn-block">
                      <i class="fab fa-facebook-f fa-fw"></i> {% trans "Login with Facebook" %}
                    </a>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'accounts:password_reset' %}">{% trans "Forgot Password?" %}</a>
                  </div>
                    <br><a class="small" href="{% url 'accounts:global_signup' %}">{% trans "Create an Account" %}</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>
    <!--</div>-->
</section>
<br>
<br><br><br><br><br>
{% endblock%}

server/accounts/templates/global-sign-up.html
{% extends "base-global.html" %}
{% load static %}
{% load i18n %}

{% block meta%}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
{% endblock%}

{% block title%}
  Login
{% endblock%}

{% block css%}
  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="css/sb-admin-2.min.css" rel="stylesheet">
{% endblock%}

{% block content%}
    <!-- Outer Row -->
<section class="signup" id="signup">
    <div class="container">

    <div class="row justify-content-center">
      <div class="col-xl-10 col-lg-12 col-md-9">
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">

        {% if social_login_error %}
          <div class="alert alert-danger" id="error_msg" role="alert">
            {{ social_login_error }}
          </div>
        {% endif %}

        {% if user_form.errors or profile_form.errors%}
        <div class="alert alert-danger" role="alert">
            {% for form in user_form %}
                {% if form.errors %}<b>{% trans form.label %}</b>{{ form.errors }}{% endif %}
            {% endfor %}
            {% for form in profile_form %}
                {% if form.errors %}<b>{% trans form.label %}</b>{{ form.errors }}{% endif %}
            {% endfor %}
        </div>
        {% endif %}
        {% csrf_token %}
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">{% trans "Create an Account" %}</h1>
              </div>
              <form class="user" method="post" action="{% url 'accounts:global_signup' %}">
                {% csrf_token %}
                <div class="form-group row">

                  <div class="col-sm-6">
                    {{ profile_form.last_name }}
                    <!-- <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Last Name">
                    -->
                  </div>
                    <div class="col-sm-6 mb-3 mb-sm-0">
                    {{ profile_form.first_name }}
                    <!--<input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="First Name">-->
                  </div>
                </div>
                <div class="form-group">
                  {{ user_form.email }}
                  <!-- <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Email Address">
                  -->
                </div>
                <div class="form-group row">
                  <!--<div class="col-sm-6 mb-3 mb-sm-0">-->
                  <div class="col-lg-12 ">
                    {{ user_form.password1 }}
                    <!-- <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
                    -->
                  </div>

                  <div class="col-lg-12 mt-3 ">
                    <!--<br>-->
                      {{ user_form.password2 }}
                    <!-- <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repeat Password">
                    -->
                  </div>
                </div>
                <div class="confirm-section">
                    <button id="submit_button" class="btn btn btn-primary btn-user btn-block confirm">
                        {% trans "Register Account" %}
                    </button>
                </div>
                <!--<hr>-->
                <!--<a href="index.html" class="btn btn-google btn-user btn-block">-->
                  <!--<i class="fab fa-google fa-fw"></i> Register with Google-->
                <!--</a>-->
                <!--<a href="index.html" class="btn btn-facebook btn-user btn-block">-->
                  <!--<i class="fab fa-facebook-f fa-fw"></i> Register with Facebook-->
                <!--</a>-->
              </form>
              <!--<hr>-->
              <div class="text-center">
                <a class="small" href="{% url 'accounts:global_login' %}">{% trans "Already have an account? Login" %}</a>
              </div>
            </div>
          </div>
        </div>
    </div>
    </div>
    </div>
    </div>
    </div>
</section>
{% endblock%}

server/accounts/templates/product_site_base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}
<!DOCTYPE HTML>

<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" type="image/png" href="{% static 'assets/images/favicon-wp.ico'%}" />
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/product_header.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/style_sp.css' %}" rel="stylesheet" />
    {% block css  %}{% endblock %}
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
    {% block js  %}{% endblock %}
    <script>
    function postLanguageChanger(code){
        var form = document.getElementById('language-changer');
        form.language.value = code;
        form.submit();
    }


    //for sp
    $(function(){
        fade('.toggleWrap');
    });
    function fade(elm){
        var $fade = $(elm),
            $body = $('body');
        $fade.addClass('hide');
        $('#toggle').on('click', function(){
            $fade.toggleClass('hide').addClass('animation');
            $('.trigger').toggleClass('active');
            if ($fade.hasClass('hide')) {
                $body.removeClass('no-scroll').off('.noScroll');
            } else {
                $body.addClass('no-scroll').on('touchmove.noScroll', function(e){
                    e.preventDefault();
                });
            }
        });
    }
    </script>

</head>
<body>
<div id="contents_wrapper">
<!-- Header -->
<form id="language-changer" action="{% url 'set_language' %}" method="post" style="display: none;">
    {% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}" />
    <input name="language" type="hidden" value="" />
</form>
<div class="navbar">
	  <h1><a href="https://services.sms-datatech.co.jp/pig-data/">Home</a></h1>
	  <ul>
	    <li><a href="https://services.sms-datatech.co.jp/pig-data/product/">Product</a></li>
	    <li><a href="https://services.sms-datatech.co.jp/pig-data/usecase/">Usecase</a></li>
	    <li><a href="https://services.sms-datatech.co.jp/pig-data/pricing_dev/">Pricing</a></li>
	    <li><a href="https://services.sms-datatech.co.jp/pig-data/blog/">Blog</a></li>
	    <li><a href="https://services.sms-datatech.co.jp/pig-data/helpcenter/">HelpCenter</a></li>
	    <li><a href="https://services.sms-datatech.co.jp/pig-data/about-us/" class="active">About Us</a></li>
      <!--
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{% if LANGUAGE_CODE == "en" %}English{% else %}日本語{% endif %}<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                {% for language in languages %}
                    <li>
                        {% if language.code == LANGUAGE_CODE %}
                            <a>{{ language.name_local }}</a>
                        {% else %}
                            <a href="#" onclick="postLanguageChanger('{{ language.code }}'); return false;">{{ language.name_local }}</a>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </li>
        -->
      <li class="login_list"><a href="{% url 'accounts:login' %}" class="active login_btn">ログイン</a></li>
	  </ul>

    <!-- SP -->
    <!--hamburger button -->
    <div id="toggle" class="sp_only">
        <div class="trigger">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
    <!-- Full Screeen Part -->
    <div class="toggleWrap sp_only">
        <ul class="mainNav">
            <li><a class="navItem" href="/pig-data/product/">Product</a></li>
            <li><a class="navItem" href="/pig-data/usecase/">Usecase</a></li>
            <li><a class="navItem" href="/pig-data/pricing/">Pricing</a></li>
            <li><a class="navItem" href="/pig-data/blog/">Blog</a></li>
            <li><a class="navItem" href="/pig-data/helpcenter/">HelpCenter</a></li>
            <li><a class="navItem" href="/pig-data/about-us/">About Us</a></li>
            <li><a class="navItem" href="/login">Login</a></li>
        </ul>
    </div>
</div>

<!-- Main Part -->
{% block content %}{% endblock %}

<!-- Footer -->
<footer class="footer footer_gray">
    <div class="container-fluid">
        <nav>
            <p class="policy_link">
            	<a href="https://services.sms-datatech.co.jp/pig-data/privacy-policy/"><u>Privacy Policy</u></a>｜
            	<a href="https://services.sms-datatech.co.jp/pig-data/security-policy/"><u>Security Policy</u></a>｜
            	<a href="https://www.sms-datatech.co.jp/"><u>運営会社HP</u></a>
            </p>
        </nav>
        <p class="copyright">
            ©
            <script>
            document.write(new Date().getFullYear())
            </script>
            SMS DataTech all right reserved.
        </p>
    </div>
</footer>
</div>

</body>
</html>