server/accounts/urls.py
from . import views
from . import views as core_views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    # url(r'home/$', core_views.home, name='home'),
    url(r'products/$', core_views.product, name='product'),
    url(r'learn/$', core_views.learn, name='learn'),
    url(r'about/$', core_views.about, name='about'),

    #url(r'testing/(?P<pid>[^/]+)$', core_views.testing, name='testing'),
    url(r'pricing/$', core_views.pricing, name='pricing'),
    url(r'^login/', views.login, name='login'),

    #url(r'^$', auth_views.logout, {'next_page': 'home'}, name='logout'),
    url(r'logout/$', views.logout_view, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^signup-confirm/$', core_views.signupConfirm, name='signupConfirm'),
    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    url(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
    url(r'^error/$', core_views.error, name='error'),
    url(r'downloadtool/$', views.downloadtool, name='downloadtool'),
    url(r'json/(?P<value>\d{3}).json', views.postal_json, name='postal_json_data'),
    url(r'account_activation/$', core_views.account_activation, name='account_activation'),

    # ---------------Password Reset------------------------------
    url(r'^password_reset/$', auth_views.password_reset,
        {'email_template_name': 'registration/password_reset_email.html',
         'subject_template_name': 'registration/password_reset_subject.txt',
         'post_reset_redirect': 'accounts:password_reset_done',
         'from_email': 'no-reply@sms-datatech.co.jp',
         }, name='password_reset'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^password_reset/done/$', auth_views.password_reset_done,
        {'template_name': 'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[^/]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    # global
    url(r'^$', core_views.global_home, name='global_home'),
    url(r'global/login/$', core_views.global_login, name='global_login'),
    url(r'global/contact/$', core_views.global_contact, name='global_contact'),
    url(r'global/signup/$', core_views.global_signup, name='global_signup'),

    url(r'resend_link/$', core_views.ResendLinkView.as_view(), name='resend_link'),
    url(r'resend_link_done/$', core_views.ResendLinkDoneView.as_view(), name='resend_link_done'),
]

server/dashboard/urls.py
from . import views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls.conf import path
from django.conf.urls.i18n import i18n_patterns


app_name = 'dashboard'

urlpatterns = [
    path(r'home/', views.index, name = 'index'),
    path(r'upgrade/', views.upgrade, name='upgrade'),
    path(r'notification_settings/', views.notification_setting, name='notification_setting'),
    path(r'delete_account/', views.delete_account, name='delete_account'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^project/list/$', views.project_list, name='project_list'),
    url(r'^project/list/i18n/', include('django.conf.urls.i18n')),
    #path(r'project/schedule/', views.project_schedule, name = 'project_schedule'),
    path(r'settings/', views.settings, name='settings'),
    path(r'notification/change/', views.notification_change, name='notification_change'),
    url(r'account_setting_basic/$', views.account_setting_basic, name='account_setting_basic'),
    url(r'profile_change/$', views.profile_change, name='profile_change'),
    url(r'profile_change_finish/$', views.profile_change_finish, name='profile_change_finish'),
    url(r'password_change/$', views.PasswordChange.as_view(), name='password_change'),
    url(r'password_change_finish/$', views.password_change_finish, name='password_change_finish'),
    url(r'agreement_payment/$', views.agreement_payment, name='agreement_payment'),
    url(r'payment_change_bank/$', views.payment_change_bank, name='payment_change_bank'),
    url(r'payment_change_credit/$', views.payment_change_credit, name='payment_change_credit'),
    url(r'payment_change_finish/$', views.payment_change_finish, name='payment_change_finish'),
    url(r'product_download/$', views.product_download, name='product_download'),
    url(r'system_error/$', views.system_error, name='system_error'),
    # url(r'cancel/$', views.cancel, name='cancel'),
    # url(r'cancel_finish/$', views.cancel_finish, name='cancel_finish'),
    path(r'ajax/$', views.managefiletype, name='managefiletype'),
    path(r'ajax1/$', views.edit_project, name='edit_project'),
    path(r'ajax2/$', views.edit_keyword, name='edit_keyword'),
    path(r'update/profile/', views.update_profile, name='update_profile'),
    path(r'project/data_order/', views.data_order, name='data_order'),
    path(r'project/data_order_form/', views.data_order_form, name='data_order_form'),
    path(r'project/data_order_confirm/', views.data_order_confirm, name='data_order_confirm'),
    path(r'project/data_order_done/', views.data_order_done, name='data_order_done'),

    #path(r'ScheduleForm/', views.schedule_form, name = 'schedule_form'),
    url(r'run/(?P<pid>[^/]+)$', views.run, name='run'),
    path(r'zip_data/(?P<pid>[^/]+)$', views.zip_data, name='zip_data'),
    path(r'delete/(?P<str:cname>[^/]+)$', views.delete_category, name='delete_category'),
    path(r'delete/(?p<pid>[^/]+)$', views.delete_project, name='delete_project'),
    path(r'delete_execution/(?P<pid>[^/]+)/(?P<eid>[^/]+)$', views.delete_execution, name='delete_execution'),
    url(r'product/$', views.product_type, name='product_type'),
    url(r'project/details/(?P<pid>[^/]+)$', views.project_details, name='project_details'),
    url(r'get_project/', views.get_project, name='get_project'),
    url(r'auto_refresh/', views.auto_refresh, name='auto_refresh'),

    url(r'email_change/$', views.email_change, name='email_change'),

    #---------Payment-------------------------------------------
    url(r'^cart$', views.ShowCartView.as_view(), name='cart'),
    #url(r'^create-payment$', views.CreatePaymentView.as_view(), name='create-payment'),
    #url(r'^execute-payment$', views.ExecutePaymentView.as_view(), name='execute-payment'),
    url(r'upgrade/payment', views.ExecutePaymentView, name='ExecutePaymentView'),
]

server/global_dashboard/urls.py
from . import views
from . import  analyze as analyze_views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = 'global_dashboard'

urlpatterns = [
    url(r'global/home/$', views.global_home, name='index'),
    url(r'global/new/project$', views.new_project, name='new_project'),
    url(r'global/projects/$', views.global_project_list, name='all_projects'),
    url(r'ajax/(?P<uid>[^/]+)/(?P<pid>[^/]+)/(?P<eid>[^/]+)/(?P<ft>[^/]+)$', views.product_type, name='product_type'),
    url(r'running/(?P<pid>[^/]+)$', views.run_now, name='run_now'),
    path(r'global/delete/(?p<pid>[^/]+)$', views.global_delete_project, name='global_delete_project'),
    url(r'^project/list/i18n/', include('django.conf.urls.i18n')),
    url(r'global/profile/$', views.profile, name='profile'),
    url(r'global/setting/$', views.setting, name='setting'),
    url(r'global/activity_log/$', views.activity_log, name='activity_log'),
    url(r'global/feedback/$', views.post_feedback, name='feedback'),
    url(r'global/instructions/$', views.instructions, name='instructions'),
    path(r'ajax_project/$', views.edit_project, name='edit_project'),
    path(r'ajax_keyword/$', views.edit_keyword, name='edit_keyword'),

    url(r'global/profile/$', views.profile, name='profile'),
    url(r'global/analyze/$', analyze_views.analyze, name='analyze'),
    url(r'global/activity/$', views.activity, name='activity'),
    url(r'global/settings/$', views.settings, name='settings'),

    url(r'global/data_order/', views.data_order, name='data_order'),
    url(r'global/data_order_form/', views.data_order_form, name='data_order_form'),
    url(r'global/data_order_confirm/', views.data_order_confirm, name='data_order_confirm'),
    url(r'global/data_order_done/', views.data_order_done, name='data_order_done'),
    url(r'global/password_change/$', views.PasswordChange.as_view(), name='password_change'),
    url(r'global/password_change_finish/$', views.password_change_finish, name='password_change_finish'),
    url(r'global/email_change/$', views.email_change, name='email_change'),
    url(r'global/cancel/$', views.cancel, name='cancel'),
    url(r'global/cancel_finish/$', views.cancel_finish, name='cancel_finish'),
]

server/saas/urls.py
from . import views as core_views
from django.conf.urls import url

app_name = 'saas'

urlpatterns = [
    url(r'^saas/start/', core_views.start, name='start'),
    url(r'^saas/getLogin', core_views.get_login, name='get_login'),
    url(r'^saas/content', core_views.url_content_sel, name='url_content_sel'),
    url(r'^saas/procedure', core_views.get_procedure, name='get_procedure'),
    url(r'^saas/', core_views.process, name='process'),
    url(r'^pigdata-saas/', core_views.pigdata, name='pigdata'),
]

server/web_rpa/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    #path('', RedirectView.as_view(url='dashboard')),
    path('', include('accounts.urls')),
    path('api/v1/core/', include('api_v1.core.urls')),
    path('api/v1/feedback/', include('api_v1.feedback.urls')),
    #path('api/v1/scheduling/', include('api_v1.scheduling.urls')),
    path('api/v1/scraping/', include('api_v1.scraping.urls')),
    path('admin/', admin.site.urls),
    path('', include('saas.urls')),
    path('', include('dashboard.urls')),
    path('', include('global_dashboard.urls')),
    path('email/', include('email_sys.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('', include('social_django.urls', namespace='social')),
]


server/dashboard/models.py
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db.models.signals import post_save

from api_v1.scraping.models import Execution
from api_v1.scraping.models import Project
from django_celery_results.models import TaskResult

from django.utils import timezone

from celery.signals import task_prerun, task_postrun
import celery.states as celery_state

from api_v1.scraping.tasks import task_scrape

@task_prerun.connect
def pre_run(sender, task_id, task, *args, **kwargs):
    task.__task_starttime = timezone.now()
    return

@task_postrun.connect
def post_run(sender, task_id, task, retval, state,  *args, **kwargs):
    end_time = timezone.now()
    start_time = getattr(task, "__task_starttime", None)

    #check
    #print(isinstance(sender, type(task_scrape)))
    #if(sender == task_scrape):
    if(not(start_time is None)):
        if(sender.name == task_scrape.name):
            #task_scrape task
            try:
                exec_time = end_time - start_time
                task_project = Project.objects.get(id=kwargs['args'][1])
                task_result = TaskResult.objects.get(task_id=task_id)
                #task_state is 0 for every completed state (FAILED, REVOKED) other than success
                task_state = True if state == celery_state.SUCCESS else False
                
                res = Execution.objects.create(task=task_result, status=task_state, project=task_project, 
                                            date_executed=start_time, end_time=end_time, exec_time=exec_time)
            except Exception as e:
                print("task_postrun exception:", e)
                import traceback
                print(traceback.print_tb(e.__traceback__))
        else:
            #Other tasks
            pass
    else:
        print("task_starttime variable NOT FOUND!!! Could not write the task in Execution table!!!")
    return

server/dashboard/templates/extra/data.html
{% load static %}
{% load i18n %}
{% language 'en' %}
<!DOCTYPE html>

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png'%}" />
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png'%}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>{% block title %}Welcome-PigData{% endblock %}</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <!-- Bootstrap core CSS     -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <!--  Material Dashboard CSS    -->
    <link href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet" />
    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'assets/css/demo.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/dropdown.css' %}" rel="stylesheet" />
        <!--  Button CSS  -->
    <link href="{% static 'assets/css/button.css' %}" rel="stylesheet" />

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
</head>

<body>
<div class="wrapper">
<div class="sidebar" data-color="purple" data-image="{% static 'assets/img/sidebar-1.jpg' %}">
    <!--
Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

Tip 2: you can also add an image using data-image tag
-->
    <div class="logo"><a href="http://www.sms-datatech.co.jp" class="simple-text">PigData</a></div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            <li>
                <a href="{% url 'dashboard:index' %}">
                    <i class="material-icons">dashboard</i>
                    <p>{% trans "Dashboard" %}</p>
                </a>
            </li>

            <li class="active">
                <a href="">
                    <i class="material-icons">content_paste</i>
                    <p>{% trans "Project Data" %}</p>
                </a>
            </li>
            <!--
            <li>
                <a href="{% url 'dashboard:project_schedule' %}">
                    <i class="material-icons">library_books</i>
                    <p>{% trans "Project Schedule" %}</p>
                </a>
            </li>
            -->
            <li>
                <a href="{% url 'dashboard:setting' %}">
                    <i class="material-icons">bubble_chart</i>
                    <p>{% trans "Setting" %}</p>
                </a>
            </li>
            <li> </li>
            <li>
                <a href="{% url 'dashboard:upgrade' %}">
                    <i class="material-icons">unarchive</i>
                    <p>{% trans "Upgrade" %}</p>
                </a>
            </li>
        </ul>
    </div>
</div>
<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!--div class="navbar-brand" href="">Welcome {{ user.username}} </div-->
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right" >
                <li>

                    {% if request.session.isClientTool != 1 %}
                    <span class="material-input"><a href="{% url 'accounts:logout' %}" class="dropdown-toggle">{% trans "Logout" %} </a></span>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="main-panel">



    <div class="content">

        <div class="container-fluid">
            <!--div align="left">
            <button class="button_base b01_simple_rollover" type='button' value=""> Refresh</button>
            <button class="button_base b01_simple_rollover" type='button' value=""> Delete </button>
            <button class="button_base b01_simple_rollover" type='button' value=""> Zip All Data</button>
            <button class="button_base b01_simple_rollover" type='button' value=""> Run Now</button>

            </div-->
            {% if num_proj != 0 %}
            {% for project in projects.values %}
            <div class="card card-plain">
                <div class="card-header" data-background-color="purple">
                    <table >
                        <!--tr>
                            <td width="20%">
                            <input type="checkbox" name="checkbox" id={{ project.id }} value="value">
                            <label for={{ project.id }}></label>
                            </td>
                            <td></td>
                        </tr-->
                        <tr>
                            <td width="40%"><h4 class="title">{% trans "Name"%}: {{ project.name }}</h4></td>
                            <td>
                                <button class="btn btn-round btn-fill btn-info" type='button' onclick="location.href='{% url 'dashboard:run' project.id %}'; download"> {% trans "Run Now" %} </button>
                                <button class="btn btn-round btn-fill btn-info" type='button' onclick="location.href='{% url 'dashboard:delete_project' project.id %}';"> {% trans "Delete Project" %}</button>
                                <button class="btn btn-round btn-fill btn-info" type='button' onclick="location.href='{% url 'dashboard:zip_data' project.id %}';" download> {% trans "Zip All Data" %}</button>
                                <button class="btn btn-round btn-fill btn-info" type='button' onclick="location.href='{% url 'dashboard:project_details' project.id %}';" download> {% trans "Project Details" %}</button>
                                <!--button class="button_base b01_simple_rollover" type='button' value="{{ project.id }}" Schedule </button-->
                            </td>
                        </tr>
                        <tr>
                            <td width="40%"><p class="category">{% trans "Created On" %}: {{ project.date_created }}</p></td>
                            <td></td>
                        </tr>

                    </table>
                </div>
                <div class="card-content table-responsive">

                    <table class="table table-hover">
                        <thead>
                        <th>{% trans "Execution Date" %}</th>
                        <th>{% trans "Status" %}</th>
                        <th>{% trans "Data" %}</th>
                        </thead>
                        <tbody>
                        {% for execution in project.executions %}
                        <tr>
                            <td>{{ execution.date_executed }}</td>
                            {% if execution.status == 1 %}
                            <td width="1"><img src="{% static 'assets/img/tick.png' %}"></td>
                            <td>
                            <form method="post" action="{% url 'dashboard:product_type' %}">
		                        {% csrf_token %}
                                <div class="styled-select blue rounded">
                                <select  id="ftype" name="filetype" onchange = "this.form.submit()">
                                    <option value={{user.id}}#{{project.id}}#{{execution.id}}#10>Download</option>
                                    <option value={{user.id}}#{{project.id}}#{{execution.id}}#1>.xls</option>
                                    <option value={{user.id}}#{{project.id}}#{{execution.id}}#2>.csv</option>
                                    <option value={{user.id}}#{{project.id}}#{{execution.id}}#3>.txt</option>
                                    <!--option value="{{user.id}}" pid="{{project.id}}" eid="{{execution.id}}" ft="2" }>.csv</option-->

                                </select>
                                    </div>
                             </form>
                            </td>
                            {% else %}
                            <td width="1"><img src="{% static 'assets/img/wait.gif' %}" alt="Running"/></td>
                            <td>{% trans "Running" %}</td>
                            {% endif %}

                        </tr>

                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="card-content table-responsive">{% trans "You do not have created any project yet. To create a project download our tool" %} <a href="{% url 'accounts:downloadtool' %}" download>PIGDATA</a></div>
            {% endif %}
        </div>
    </div>
    </div>
    <footer class="footer">
        <div class="container-fluid">
            <nav class="pull-left">
                <ul>
                    <li>
                        <a href="#">
                            {% trans "Home" %}
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            {% trans "Company" %}
                        </a>
                    </li>
                    <li>
                        <a href="#"> {% trans "Contacts" %}</a>
                    </li>
                    <li>
                        <a href="#">
                            {% trans "Blog" %}
                        </a>
                    </li>
                </ul>
            </nav>
            <p class="copyright pull-right">
                &copy;
                <script>
                            document.write(new Date().getFullYear())
                        </script>
                <a href="http://www.sms-datatech.co.jp"> SMS DATA TECH CO.</a>
            </p>
        </div>
    </footer>
</div>
</div>
</body>
<!--   Core JS Files   -->
<script src="{% static 'assets/js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/material.min.js' %}" type="text/javascript"></script>
<!--  Charts Plugin -->
<script src="{% static 'assets/js/chartist.min.js' %}"></script>
<!--  Dynamic Elements plugin -->
<script src="{% static 'assets/js/arrive.min.js' %}"></script>
<!--  PerfectScrollbar Library -->
<script src="{% static 'assets/js/perfect-scrollbar.jquery.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'assets/js/bootstrap-notify.js' %}"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Material Dashboard javascript methods -->
<script src="{% static 'assets/js/material-dashboard.js' %}"></script>
<!-- Material Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static 'assets/js/demo.js' %}"></script>
</html>
{% endlanguage %}

server/dashboard/templates/extra/pass_base.html
{% load static %}
{% load i18n %}
{% language 'en' %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>PigData: {% trans "Sign Up" %}</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
	<!--[if lte IE 9]><link rel="stylesheet" href="static/css/ie9.css" /><![endif]-->
	<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div id="wrapper">

    <header id="header">
        <nav>
            <ul>
                <li><a href="{% url 'accounts:login' %}">{% trans "Home" %}</a></li>
            </ul>
        </nav>
    </header>
    </br></br>
    {% block content%} {% endblock%}
</div>

<!-- Footer -->
<footer id="footer">
    <p class="copyright"><a href="https:sms-datatech.co.jp">&copy; SMS DataTech Co. </a></p>
</footer>

</div>
<!-- BG -->
<div id="bg"></div>
<!-- Scripts -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/skel.min.js' %}"></script>
<script src="{% static 'assets/js/util.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>
{% endlanguage %}

server/dashboard/templates/extra/project_details.html
{% load static %}
{% load i18n %}
{% language 'en' %}
<!DOCTYPE html>

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png'%}" />
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png'%}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>{% block title %}Welcome-PigData{% endblock %}</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <!-- Bootstrap core CSS     -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <!--  Material Dashboard CSS    -->
    <link href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet" />
    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'assets/css/demo.css' %}" rel="stylesheet" />
        <!--  Button CSS  -->
    <link href="{% static 'assets/css/button.css' %}" rel="stylesheet" />
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
</head>

<body>
<div class="wrapper">
    Project Details:
    {% block content%} {% endblock%}
    <footer class="footer">
        <div class="container-fluid">
            <nav class="pull-left">
                <ul>
                    <li>
                        <a href="#">
                            {% trans "Home" %}
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            {% trans "Company" %}
                        </a>
                    </li>
                    <li>
                        <a href="#"> {% trans "Contacts" %}</a>
                    </li>
                    <li>
                        <a href="#">
                            {% trans "Blog" %}
                        </a>
                    </li>
                </ul>
            </nav>
            <p class="copyright pull-right">
                &copy;
                <script>
                            document.write(new Date().getFullYear())
                        </script>
                <a href="http://www.sms-datatech.co.jp"> SMS DATA TECH CO.</a>
            </p>
        </div>
    </footer>
</div>
</div>
</body>
<!--   Core JS Files   -->
<script src="{% static 'assets/js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/material.min.js' %}" type="text/javascript"></script>
<!--  Charts Plugin -->
<script src="{% static 'assets/js/chartist.min.js' %}"></script>
<!--  Dynamic Elements plugin -->
<script src="{% static 'assets/js/arrive.min.js' %}"></script>
<!--  PerfectScrollbar Library -->
<script src="{% static 'assets/js/perfect-scrollbar.jquery.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'assets/js/bootstrap-notify.js' %}"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Material Dashboard javascript methods -->
<script src="{% static 'assets/js/material-dashboard.js' %}"></script>
<!-- Material Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static 'assets/js/demo.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {

        // Javascript method's body can be found in assets/js/demos.js
        demo.initDashboardPageCharts();

    });
</script>
<script>
$(document).ready(function() {
var modal = document.getElementById('myModal');
var span = document.getElementsByClassName("close")[0];

$(".myBtn").click(function() {

modal.style.display = "block";

document.getElementById('pid_btn').value = $(this).val();
});

$(".close").click(function() {
modal.style.display = "none";
});

window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}

});
</script>

</html>
{% endlanguage %}