server/accounts/urls.py
from . import views
from . import views as core_views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    # url(r'home/$', core_views.home, name='home'),
    url(r'products/$', core_views.product, name='product'),
    url(r'learn/$', core_views.learn, name='learn'),
    url(r'about/$', core_views.about, name='about'),

    #url(r'testing/(?P<pid>[^/]+)$', core_views.testing, name='testing'),
    url(r'pricing/$', core_views.pricing, name='pricing'),
    url(r'^login/', views.login, name='login'),

    #url(r'^$', auth_views.logout, {'next_page': 'home'}, name='logout'),
    url(r'logout/$', views.logout_view, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^signup-confirm/$', core_views.signupConfirm, name='signupConfirm'),
    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    url(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
    url(r'^error/$', core_views.error, name='error'),
    url(r'downloadtool/$', views.downloadtool, name='downloadtool'),
    url(r'json/(?P<value>\d{3}).json', views.postal_json, name='postal_json_data'),
    url(r'account_activation/$', core_views.account_activation, name='account_activation'),

    # ---------------Password Reset------------------------------
    url(r'^password_reset/$', auth_views.password_reset,
        {'email_template_name': 'registration/password_reset_email.html',
         'subject_template_name': 'registration/password_reset_subject.txt',
         'post_reset_redirect': 'accounts:password_reset_done',
         'from_email': 'no-reply@sms-datatech.co.jp',
         }, name='password_reset'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^password_reset/done/$', auth_views.password_reset_done,
        {'template_name': 'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[^/]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    # global
    url(r'^$', core_views.global_home, name='global_home'),
    url(r'global/login/$', core_views.global_login, name='global_login'),
    url(r'global/contact/$', core_views.global_contact, name='global_contact'),
    url(r'global/signup/$', core_views.global_signup, name='global_signup'),

    url(r'resend_link/$', core_views.ResendLinkView.as_view(), name='resend_link'),
    url(r'resend_link_done/$', core_views.ResendLinkDoneView.as_view(), name='resend_link_done'),
]

server/dashboard/urls.py
from . import views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls.conf import path
from django.conf.urls.i18n import i18n_patterns


app_name = 'dashboard'

urlpatterns = [
    path(r'home/', views.index, name = 'index'),
    path(r'upgrade/', views.upgrade, name='upgrade'),
    path(r'notification_settings/', views.notification_setting, name='notification_setting'),
    path(r'delete_account/', views.delete_account, name='delete_account'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^project/list/$', views.project_list, name='project_list'),
    url(r'^project/list/i18n/', include('django.conf.urls.i18n')),
    #path(r'project/schedule/', views.project_schedule, name = 'project_schedule'),
    path(r'settings/', views.settings, name='settings'),
    path(r'notification/change/', views.notification_change, name='notification_change'),
    url(r'account_setting_basic/$', views.account_setting_basic, name='account_setting_basic'),
    url(r'profile_change/$', views.profile_change, name='profile_change'),
    url(r'profile_change_finish/$', views.profile_change_finish, name='profile_change_finish'),
    url(r'password_change/$', views.PasswordChange.as_view(), name='password_change'),
    url(r'password_change_finish/$', views.password_change_finish, name='password_change_finish'),
    url(r'agreement_payment/$', views.agreement_payment, name='agreement_payment'),
    url(r'payment_change_bank/$', views.payment_change_bank, name='payment_change_bank'),
    url(r'payment_change_credit/$', views.payment_change_credit, name='payment_change_credit'),
    url(r'payment_change_finish/$', views.payment_change_finish, name='payment_change_finish'),
    url(r'product_download/$', views.product_download, name='product_download'),
    url(r'system_error/$', views.system_error, name='system_error'),
    # url(r'cancel/$', views.cancel, name='cancel'),
    # url(r'cancel_finish/$', views.cancel_finish, name='cancel_finish'),
    path(r'ajax/$', views.managefiletype, name='managefiletype'),
    path(r'ajax1/$', views.edit_project, name='edit_project'),
    path(r'ajax2/$', views.edit_keyword, name='edit_keyword'),
    path(r'update/profile/', views.update_profile, name='update_profile'),
    path(r'project/data_order/', views.data_order, name='data_order'),
    path(r'project/data_order_form/', views.data_order_form, name='data_order_form'),
    path(r'project/data_order_confirm/', views.data_order_confirm, name='data_order_confirm'),
    path(r'project/data_order_done/', views.data_order_done, name='data_order_done'),

    #path(r'ScheduleForm/', views.schedule_form, name = 'schedule_form'),
    url(r'run/(?P<pid>[^/]+)$', views.run, name='run'),
    path(r'zip_data/(?P<pid>[^/]+)$', views.zip_data, name='zip_data'),
    path(r'delete/(?P<str:cname>[^/]+)$', views.delete_category, name='delete_category'),
    path(r'delete/(?p<pid>[^/]+)$', views.delete_project, name='delete_project'),
    path(r'delete_execution/(?P<pid>[^/]+)/(?P<eid>[^/]+)$', views.delete_execution, name='delete_execution'),
    url(r'product/$', views.product_type, name='product_type'),
    url(r'project/details/(?P<pid>[^/]+)$', views.project_details, name='project_details'),
    url(r'get_project/', views.get_project, name='get_project'),
    url(r'auto_refresh/', views.auto_refresh, name='auto_refresh'),

    url(r'email_change/$', views.email_change, name='email_change'),

    #---------Payment-------------------------------------------
    url(r'^cart$', views.ShowCartView.as_view(), name='cart'),
    #url(r'^create-payment$', views.CreatePaymentView.as_view(), name='create-payment'),
    #url(r'^execute-payment$', views.ExecutePaymentView.as_view(), name='execute-payment'),
    url(r'upgrade/payment', views.ExecutePaymentView, name='ExecutePaymentView'),
]

server/saas/urls.py
from . import views as core_views
from django.conf.urls import url

app_name = 'saas'

urlpatterns = [
    url(r'^saas/start/', core_views.start, name='start'),
    url(r'^saas/getLogin', core_views.get_login, name='get_login'),
    url(r'^saas/content', core_views.url_content_sel, name='url_content_sel'),
    url(r'^saas/procedure', core_views.get_procedure, name='get_procedure'),
    url(r'^saas/', core_views.process, name='process'),
    url(r'^pigdata-saas/', core_views.pigdata, name='pigdata'),
]

server/web_rpa/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    #path('', RedirectView.as_view(url='dashboard')),
    path('', include('accounts.urls')),
    path('api/v1/core/', include('api_v1.core.urls')),
    path('api/v1/feedback/', include('api_v1.feedback.urls')),
    #path('api/v1/scheduling/', include('api_v1.scheduling.urls')),
    path('api/v1/scraping/', include('api_v1.scraping.urls')),
    path('admin/', admin.site.urls),
    path('', include('saas.urls')),
    path('', include('dashboard.urls')),
    path('', include('global_dashboard.urls')),
    path('email/', include('email_sys.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('', include('social_django.urls', namespace='social')),
]


server/saas/models.py
from django.db import models

# Create your models here.

server/saas/forms.py
from django import forms

class StartForm(forms.Form):
    start_url = forms.CharField(max_length=2000, widget=forms.TextInput(attrs={'class': 'form-control', 'id':'start_url', 'placeholder': "http://example.com"}), required=True)
    is_login = forms.BooleanField(required=False, label="check this if login required")

server/saas/templates/pg-base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}

<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png'%}" />
    <link rel="icon" type="image/png" href="{% static 'assets/images/favicon.png'%}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>{% block title %}{% endblock %}</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    {% block meta %}{% endblock %}
    <!-- Bootstrap core CSS     -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <!--  Material Dashboard CSS    -->
    <link href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet" />
    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'assets/css/demo.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/dropdown.css' %}" rel="stylesheet" />
    <!--  Button CSS  -->
    <link href="{% static 'assets/css/button.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/btnbutton.css' %}" rel="stylesheet" />
    <!--  Fonts and icons     -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>
    {% block css %}{% endblock %}
</head>

<body style="background-color: #dcf5f5; height: 100%;">
  <div id="contents_wrapper">
    <div class="wrapper">
        <!-- Header -->
        <nav class="navbar navbar-inverse nav-justified" style="background: #339999; z-index: 10000; margin-bottom: 0;">
            <div class="container-fluid">
                <form id="language-changer" action="{% url 'set_language' %}" method="post" style="display: none;">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}" />
                    <input name="language" type="hidden" value="" />
                </form>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav nav-justified main-header">
                        <li style="width: 0.001%;"><a href="{% url 'dashboard:index' %}"><img src="{% static 'assets/images/pig_side.png' %}" width="80"></a></li>
                        <li><a href="{% url 'dashboard:index' %}">{% trans "Home" %}</a></li>
                        <li><a href="{% url 'dashboard:project_list' %}">{% trans "Project" %}</a></li>
                        <li><a href="{% url 'dashboard:data_order' %}">{% trans "Data Order" %}</a></li>
                        <li><a href="/saas/start/">Demo</a></li>
                        <li><a href="https://services.sms-datatech.co.jp/pig-data/faq/">{% trans "FAQ" %}</a></li>
                        <li style="width: 0.6%; vertical-align: middle;">
                            <a class="profile-link" style="">
                                <div class="profile"><i class="fa fa-user" aria-hidden="true"></i>{{ user.last_name}}&nbsp;{{ user.first_name }}&nbsp;様</div>
                            </a>
                            <div class="popup">
                                <div><a href="{% url 'dashboard:account_setting_basic' %}">{% trans "Account" %}</a></div>
                                <div>
                                    {% for language in languages %}
                                        {% if language.code != LANGUAGE_CODE %}
                                            <a href="#" onclick="postLanguageChanger('{{ language.code }}'); return false;">{{ language.name_local }}</a>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                                {% if request.session.isClientTool != 1 %}
                                    <div><a href="{% url 'accounts:logout' %}">{% trans "Logout" %}</a></div>
                                {% endif %}
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Main Part -->
        {% block content %}{% endblock %}
    </div>
    <!-- Footer -->
    <footer class="footer footer_gray">
        <div class="container-fluid">
            <nav>
                <p class="policy_link">
                	<a href="https://services.sms-datatech.co.jp/pig-data/privacy-policy/"><u>Privacy Policy</u></a>｜
                	<a href="https://services.sms-datatech.co.jp/pig-data/security-policy/"><u>Security Policy</u></a>｜
                	<a href="https://services.sms-datatech.co.jp/pig-data/"><u>プロダクトページ</u></a>｜
                	<a href="https://www.sms-datatech.co.jp/"><u>運営会社HP</u></a>
                </p>
            </nav>
            <p class="copyright">
                ©
                <script>
                document.write(new Date().getFullYear())
                </script>
                SMS DataTech all right reserved.
            </p>
        </div>
    </footer>
  </div>
</body>
<!--   Core JS Files   -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/material.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/arrive.min.js' %}"></script>
<script src="{% static 'assets/js/perfect-scrollbar.jquery.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap-notify.js' %}"></script>
<script src="{% static 'assets/js/material-dashboard.js' %}"></script>
{% block js %}{% endblock %}
</html>

server/saas/templates/saas-base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}

<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png'%}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="icon" type="image/png" href="{% static 'assets/images/favicon.png'%}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>{% block title %}{% endblock %}</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    {% block meta %}{% endblock %}
    <!-- Bootstrap core CSS     -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />
    <!--  Material Dashboard CSS    -->
    <link href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet" />
    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'assets/css/demo.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/dropdown.css' %}" rel="stylesheet" />
    <!--  Button CSS  -->
    <link href="{% static 'assets/css/button.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/css/btnbutton.css' %}" rel="stylesheet" />
    <!--  Fonts and icons     -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>
    {% block css %}{% endblock %}
</head>

<body style="background-color: #dcf5f5; height: 100%;">
  <div id="contents_wrapper">
    <div class="wrapper">
        <!-- Header -->
        <nav class="navbar navbar-inverse nav-justified" style="background: #339999; z-index: 10000; margin-bottom: 0;">
            <div class="container-fluid">
                <form id="language-changer" action="{% url 'set_language' %}" method="post" style="display: none;">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}" />
                    <input name="language" type="hidden" value="" />
                </form>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav nav-justified main-header">
                        <li style="width: 0.001%;"><a href="{% url 'dashboard:index' %}"><img src="{% static 'assets/images/pig_side.png' %}" width="80"></a></li>
                        <li><a href="{% url 'dashboard:index' %}">{% trans "Home" %}</a></li>
                        <li><a href="{% url 'dashboard:project_list' %}">{% trans "Project" %}</a></li>
                        <li><a href="{% url 'dashboard:data_order' %}">{% trans "Data Order" %}</a></li>
                        <li><a href="/saas/start/">Demo</a></li>
                        <li><a href="https://services.sms-datatech.co.jp/pig-data/faq/">{% trans "FAQ" %}</a></li>
                        <li style="width: 0.6%; vertical-align: middle;">
                            <a class="profile-link" style="">
                                <div class="profile"><i class="fa fa-user" aria-hidden="true"></i>{{ user.last_name}}&nbsp;{{ user.first_name }}&nbsp;様</div>
                            </a>
                            <div class="popup">
                                <div><a href="{% url 'dashboard:account_setting_basic' %}">{% trans "Account" %}</a></div>
                                <div>
                                    {% for language in languages %}
                                        {% if language.code != LANGUAGE_CODE %}
                                            <a href="#" onclick="postLanguageChanger('{{ language.code }}'); return false;">{{ language.name_local }}</a>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                                {% if request.session.isClientTool != 1 %}
                                    <div><a href="{% url 'accounts:logout' %}">{% trans "Logout" %}</a></div>
                                {% endif %}
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Main Part -->
        {% block content %}{% endblock %}
    </div>
    <!-- Footer -->
    <footer class="footer footer_gray">
        <div class="container-fluid">
            <nav>
                <p class="policy_link">
                	<a href="https://services.sms-datatech.co.jp/pig-data/privacy-policy/"><u>Privacy Policy</u></a>｜
                	<a href="https://services.sms-datatech.co.jp/pig-data/security-policy/"><u>Security Policy</u></a>｜
                	<a href="https://services.sms-datatech.co.jp/pig-data/"><u>プロダクトページ</u></a>｜
                	<a href="https://www.sms-datatech.co.jp/"><u>運営会社HP</u></a>
                </p>
            </nav>
            <p class="copyright">
                ©
                <script>
                document.write(new Date().getFullYear())
                </script>
                SMS DataTech all right reserved.
            </p>
        </div>
    </footer>
  </div>
</body>
<!--   Core JS Files   -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/material.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/arrive.min.js' %}"></script>
<script src="{% static 'assets/js/perfect-scrollbar.jquery.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap-notify.js' %}"></script>
<script src="{% static 'assets/js/material-dashboard.js' %}"></script>
{% block js %}{% endblock %}
</html>

server/saas/templates/start.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}Pigdata-SaaS{% endblock %}
{% block meta %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
$(function() {
  var checkbox = $("#is_login");
  var hidden = $("#hidden_fields");
  var populate = $("#start_url");
  hidden.hide();
  checkbox.change(function() {
    if (checkbox.is(':checked')) {
      hidden.show();
      $('#login_url').prop('required', true);
      //populate.val("Dude, this input got populated!");
    } else {
      hidden.hide();
      $('#login_url').prop('required', false);
    // $("#hidden_field").val("");
    }
  });
});
</script>
{% endblock %}
{% block content %}
<!--<form action="/pigdata-saas/" method="post">-->
    <!--{% csrf_token %}-->
    <!--{{ form.as_p }}-->
    <!--<input type="submit" value="Submit">-->
<!--</form>-->

<div class="card-block" style="margin: 100px auto; width:555px; height:360px;" >
  <form action="/saas/" method="POST">
    <div style="width: 50%; margin: 0 auto; text-align: left">
    URL: <input type="text" id="start_url" name="start_url" required> </br>
    If login required: <input type="checkbox" id="is_login" name="is_login"></br>
    <div id="hidden_fields">
      Login URL: <input type="text" id="login_url" class="form-control" name="login_url">
    </div>
    <input  type="submit" class="btn btn-primary btn-fill btn-info" value="Submit">
    </div>
  </form>
</div>
{% endblock %}